auctions/urls.py
from django.urls import path

from . import views


app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("new_listing", views.new_listing, name="new_listing"),
    path("<int:id>/", views.listing, name="id"),
    path("watchlist/", views.watchlist_view, name="watchlist_view"),
    path("watchlist/<int:id>/", views.watchlist, name="watchlist"),
    path("close_listing/<int:id>/", views.close_listing, name="close_listing"),
    path("new_comment/<int:id>/", views.new_comment, name="new_comment"),
    path("categories/", views.categories, name="categories"),
    path("category_listings/<str:category>/", views.category_listings, name="category_listings"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
import requests
class User(AbstractUser):
    pass

class Listing(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    details = models.TextField(max_length=300)
    CATEGORY_CHOICES = [
        ("FOOD", "FOOD"),
        ("ELECTRONICS", "ELECTRONICS"),
        ("CLOTHING", "CLOTHING"),
        ("ACCESSORIES", "ACCESSORIES"),
        ("CONTENT", "CONTENT"),
        ("SERVICE", "SERVICE"),
        ("MUSIC", "MUSIC"),
        ("ENTERTAINMENT", "ENTERTAINMENT"),
        ("HOME EQUIPMENT", "HOME EQUIPMENT"),
        ("ART","ART"),
        ("AUTO INDUSTRY", "AUTO INDUSTRY"),
        ("PETS", "PETS"),
        ("MISC ITEMS", "MISC ITEMS"),
        ("NONE","NONE"),
    ]
    category = models.CharField(
        max_length=15,
        choices=CATEGORY_CHOICES,
        default="NONE",
    )
    created = models.DateTimeField
    image_url = models.ImageField(null=True, blank=True, upload_to='images/', editable=True,)
    active = models.BooleanField(default=True)
    time_submitted = models.DateTimeField(blank=False, default=timezone.now)
    winner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="winner")
    image_height = models.PositiveIntegerField(null=True, blank=True, editable=False, default="200")
    image_width = models.PositiveIntegerField(null=True, blank=True, editable=False, default="200")

    def __unicode__(self):
        return "{0}".format(self.image) 

    def __str__(self):
        return f"{self.title}"


class Bid(models.Model):
    bid = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    time_submitted = models.DateTimeField(blank=False, default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.bid}"


class WatchList(models.Model):
    listings = models.ManyToManyField(Listing, related_name="watched")
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.user}"


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listings = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listing_comments")
    comment = models.CharField(max_length=150, blank=False)
    time_submitted = models.DateTimeField(blank=False, default=timezone.now)
    
    def __str__(self):
        return f"{self.comment}"

auctions/forms.py
from . import models
from django import forms

class NewListingForm(forms.ModelForm):
    class Meta:
        model = models.Listing
        fields = ['title', 'details', 'category','price', 'image_url']
        # widgets = {
        #     'fields': forms.TextInput(attrs={'class': 'form-column'}),
        # }


class NewBidForm(forms.ModelForm):
    class Meta:
        model = models.Bid
        fields = ['bid']


class NewCommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['comment']

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from auctions import forms
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import AnonymousUser

from .models import *


def index(request):
    return render(request, "auctions/index.html", {
        "listings": Listing.objects.filter(active=True),
        "bids" : Bid.objects.all(),
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "messsage": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


def new_listing(request):
    # save new listing if it is valid
    if request.method == "POST":
        form = forms.NewListingForm(request.POST, request.FILES)
        if form.is_valid():
            listing = form.save(commit=False)
            listing.user = request.user            
            listing.save()
            return HttpResponseRedirect(reverse("auctions:index"))
        
    # Return the user to a page to add a new listing
    else:
        return render(request, "auctions/new_listing.html", {
            "new_listing_form" : forms.NewListingForm()
        })



def listing(request, id):
    # get requested listing, return listing
    if request.method == "GET":
        if request.user.is_authenticated:
            try:
                listing = Listing.objects.get(id=id)
                try:
                    watchlist = WatchList.objects.get(user=request.user)
                except WatchList.DoesNotExist:
                    watchlist = WatchList(user=request.user)
                return render(request, "auctions/listing.html", {
                    "listing": listing,
                    "title": listing.title,
                    "watchlist" : watchlist,
                    "NewBidForm" : forms.NewBidForm(),
                    "NewCommentForm": forms.NewCommentForm(),
                    "comments":Comment.objects.filter(listings=listing)
                })
            except Listing.DoesNotExist or TypeError or NameError or None:
                return render(request, "auctions/listing.html", {
                    "listing": None,
                    "title": listing.title,
                    "error": 'Error. No listing found.',
                    "watchlist" : WatchList.objects.get(user=request.user),
                    "NewBidForm" : forms.NewBidForm(),
                    "NewCommentForm": forms.NewCommentForm(),
                    "comments":Comment.objects.filter(listings=listing)
                })
        else:
            listing = Listing.objects.get(id=id)
            return render(request, "auctions/listing.html", {
                "listing": listing,
                "comments":Comment.objects.filter(listings=listing),
            })
    # handle new bid attempt on listing page
    else:
        bid_form = forms.NewBidForm(request.POST)
        bid_form.save(commit=False)


        listing = Listing.objects.get(id=id)
        try:
            WatchList.objects.get(user=request.user)

            if bid_form.is_valid():
                listing_bid = Bid.objects.get(listing=listing)

                if  bid_form.cleaned_data['bid'] < listing.price:
                    return render(request, "auctions/listing.html", {
                        "error" : "The bid submitted is equal to or less than the starting price.",
                        "listing": listing,
                        "watchlist" : WatchList.objects.get(user=request.user),
                        "NewBidForm" : forms.NewBidForm(),
                        "NewCommentForm": forms.NewCommentForm(),
                        "comments":Comment.objects.filter(listings=listing)
                    })
                if bid_form.cleaned_data['bid'] <= listing_bid.bid:

                    return render(request, "auctions/listing.html", {
                        "error" : "You uh... you sure you don't want to bid higher? You should bid higher.",
                        "listing": listing,
                        "watchlist" : WatchList.objects.get(user=request.user),
                        "NewBidForm" : forms.NewBidForm(),
                        "NewCommentForm": forms.NewCommentForm(),
                        "comments":Comment.objects.filter(listings=listing)
                    })
                listing_bid.bid = bid_form.cleaned_data['bid']
                listing_bid.save()
                return render (request, "auctions/listing.html", {
                        "listing": listing,
                        "watchlist" : WatchList.objects.get(user=request.user),
                        "NewBidForm" : forms.NewBidForm(),
                        "NewCommentForm": forms.NewCommentForm(),
                        "comments":Comment.objects.filter(listings=listing)
                })
        except Bid.DoesNotExist or None: # FIX TO WATCHLIST.DOESNOTEXIST?

            new_bid = bid_form.cleaned_data['bid']
            if  listing.price > new_bid:
                bid_form.save(commit=False)
                return render(request, "auctions/listing.html", {
                    "error" : "The bid submitted is equal to or less than the listing price.",
                    "listing": listing,
                    "watchlist" : WatchList.objects.get(user=request.user),
                    "NewBidForm" : forms.NewBidForm(),
                    "NewCommentForm": forms.NewCommentForm(),
                    "comments":Comment.objects.filter(listings=listing)
                })
            else:
                listing_bid = Bid.objects.create(user = request.user, listing=listing)
                listing_bid.bid = bid_form.cleaned_data['bid']
                listing_bid.save()
                return render (request, "auctions/listing.html", {
                        "listing": listing,
                        "watchlist" : WatchList.objects.get(user=request.user),
                        "NewBidForm" : forms.NewBidForm(),
                        "NewCommentForm": forms.NewCommentForm(),
                        "comments":Comment.objects.filter(listings=listing)
                })

@login_required
def watchlist(request, id):

    listing = Listing.objects.get(id=id)
    # try to get users watchlist
    try:
        listing_in_watchlist = WatchList.objects.get(listings= listing,user=request.user)
    except WatchList.DoesNotExist:
        listing_in_watchlist = None
    #remove listing from watchlist if listing is in users watchlist
    if listing_in_watchlist != None:
        listing_in_watchlist.listings.remove(listing)
        listing_in_watchlist.save()


        return render(request, "auctions/listing.html", {
            "listing": listing,
            "watchlist" : WatchList.objects.get(user=request.user),
            "NewBidForm" : forms.NewBidForm(),
            "NewCommentForm": forms.NewCommentForm(),
            "comments":Comment.objects.filter(listings=listing)
        })   
    else:
    # if listing not in user watchlist, add listing to watchlist
        try:
            watched_listings = WatchList.objects.get(user=request.user)
        except WatchList.DoesNotExist:
            watched_listings = WatchList.objects.create(user=request.user)

        watched_listings.listings.add(listing)
        watched_listings.save()
        return render(request, "auctions/listing.html", {
            "listings": watched_listings,
            "listing": listing,
            "title": listing.title,
            "watchlist" :  WatchList.objects.get(user=request.user),
            "NewBidForm" : forms.NewBidForm(),
            "NewCommentForm": forms.NewCommentForm(),
            "comments":Comment.objects.filter(listings=listing)
        })


@login_required
def watchlist_view(request):
    # try to go to users watchlist
    try:
        user_watchlist = WatchList.objects.get(user=request.user)
        return render(request, "auctions/watchlist.html", {
            "watchlist" : user_watchlist,
        })   
    # if user has no watchlist, create one and go to it
    except WatchList.DoesNotExist:  
        user_watchlist = WatchList(user=request.user)
        user_watchlist.save()
        return render(request, "auctions/watchlist.html", {
            "watchlist" : user_watchlist,

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2 class="header" id="listing-title">Categories</h2>

    <ul class="nav-row">
        {% for category,value in categories %}
        <li class="nav-link">
            <a href="{% url 'auctions:category_listings' category %}">
                {{category}}
            </a>
        </li>
        {% endfor %}
    </ul>

{% endblock %}                

auctions/templates/auctions/category_listings.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2 class="header" id="listing-title">Category Listings</h2>

    <ul style="list-style:none;">
        {% for listing in listings %}
        <li class="nav-link">
            <a href="{% url 'auctions:id' listing.id %}">
                {{listing}}
            </a>
        </li>
        {% endfor %}
    </ul>

{% endblock %}                

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}

    <div class="col">

        <h2 class="col header">Active Listings</h2>
        
        <ul style="list-style:none;">
            {% if listings %}
            
            {% for listing in listings %}
            
            <div class="card listing" >
                <!-- <li > -->
                
                    <h4 class="string">
                        <a class="string" href="{% url 'auctions:id' listing.id %}">
                            {{ listing.title }}
                        </a>
                    </h4>
                    
                    <!-- <ul> -->
                        <h6>
                            Owner:
                            <span style="font-weight: normal; color:gray;">
                                {{ listing.user }}
                            </span>
                        </h6>

                        
                        <div class="img-border">
                                {% if listing.image_url %}

                                <img class="img-thumbnail"style="display:inline-block; height:100%; width:100%;object-fit: contain;"src= "{{ listing.image_url.url }}" >
                                {% else %}
                                
                                <img class="img-thumbnail"style="display:inline-block; height:100%; width:100%;object-fit: contain;"src= "https://st4.depositphotos.com/14953852/24787/v/600/depositphotos_247872612-stock-illustration-no-image-available-icon-vector.jpg" >

                                {% endif %}
                            </div>
                            <div style="display:inline;position:absolute;left:14em;bottom:1em;">
                                
                                <h6>
                                    <span>
                                        Price: ${{ listing.price }}
                                    </span>
                                </h6>
                                <h6>
                                    Description: 
                                    <span style="font-weight: normal; color:gray;">
                                        {{ listing.details }}
                                    </span>
                                </h6>
                                <h6 class="string">
                                    <span style="font-weight: normal; color:gray;font-size:smaller">
                                        {{ listing.category }}
                                    </span>
                                </h6>
                        </div>
                    <!-- </ul> -->
                    
                <!-- </li> -->
            </div>
            <hr>
            {% endfor %}
            
            {% else %}
            
            Currently no active listings
            
            {% endif %}
        </ul>
    </div>

{% endblock %}                

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="col container">
            <h1 class="header app-header">Auctions</h1>
                <div class="signed_in">
                    {% if user.is_authenticated %}
                        <div>
                            Signed in as <strong>{{ user.username }}</strong>.
                        </div>
                    {% else %}
                    <div>

                        Not signed in.
                    </div>
                    {% endif %}
                </div>
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'auctions:new_listing' %}">New Listing</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a class="nav-link" href="{% url 'auctions:watchlist_view' %}">Watchlist</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                        </li>
                    {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                            </li>
                    {% endif %}
                </li>
            </ul>
        </div>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="col">
    <div class="col">

        
        {% if listing %}
        
        {% if error %}
        {{ error }}
        {% endif %}
        
        <h2 class="header" > 
            {{ listing.title }} 
                <!-- watchlist button -->

                <form style="margin:0px; display:inline-block; position:absolute; top:-5px; left:331px;" action="{% url 'auctions:watchlist' listing.id %}">
                    <button class="watchlist-button" type="submit" >
                        {% if listing in watchlist.listings.all %}
                            <a>
                                Unwatch
                            </a>
                            {% else %}
                            <a>
                                Watch
                            </a>
                        {% endif %}
                    </button>
                </form>
                


        </h2>
        
        <div class="col"> 
            
            <ul  >
                <h6>
                    owner:
                    <span style="font-weight: normal; color:gray;">
                        {{ listing.user }}
                    </span>
                </h6>

                <div class="img-border">

                    {% if listing.image_url %}
                    
                    <img class="img-thumbnail"style="display:inline-block; height:100%; width:100%;object-fit: contain;"src= "{{ listing.image_url.url }}" >
                    {% else %}
                    
                    <img class="img-thumbnail"style="display:inline-block; height:100%; width:100%;object-fit: contain;"src= "https://st4.depositphotos.com/14953852/24787/v/600/depositphotos_247872612-stock-illustration-no-image-available-icon-vector.jpg" >
                    
                    {% endif %}
                </div>
                <div style="display:inline;position:absolute;left:17em;bottom:1em;">

                    <h6>
                        <span>
                            Price: ${{ listing.price }}
                        </span>
                    </h6>
                    <h6>
                        Description: 
                        <span style="font-weight: normal; color:gray;">
                            {{ listing.details }}
                        </span>
                    </h6>
                    <h6>
                        Category: 
                        <span style="font-weight: normal; color:gray;">
                            {{ listing.category }}
                        </span>
                    </h6>
                </div>
            </ul>
        </div>
    </div>

    

    {% if user.is_authenticated %}
    
    
    <div class="">
    
        {% if listing.winner %}
        <div style="padding-left:50px;" class="col">

            This auction is closed. 
            
            {% if listing.winner == request.user %}
            Congratulations! You are the winner!
            {% endif %}
            
            {% if listing.user == request.user %}
            
            The winner is: {{ listing.winner }}    
            {% endif %}
        </div>
            {% else %}
            <!-- New bid form -->
            <form method="POST" action="{% url 'auctions:id' listing.id %}">
                {% csrf_token %}
                {{ NewBidForm}}
                <button class="btn btn-outline-primary" type="submit">
                    Place Bid
                </button>
            </form>
            
            
            {% if listing.user == user %}
            
            <form action="{% url 'auctions:close_listing' listing.id %}">
                <button class="btn btn-outline-primary" type="submit">
                    Close Listing
                </button>
            </form>
            {% endif %}
    </div>
    
        <hr>
        <h3 class="header" id="comments-title">
            Comments:
        </h3>
        {% if comments %}
        {% for comment in comments %}
        <ul class="comments">
            <li>
                {{ comment }}
                
                <div class="comment_user">
                    by: {{comment.user}}
                </div>
                
            </li>
        </ul>
        {% endfor %}
        {% else %}
        <div class="col">
            No comments.
        </div>
        {% endif %}

    <form method="POST" action="{% url 'auctions:new_comment' listing.id %}">
        {% csrf_token %}
        {% for field in NewCommentForm %}

        {{ NewCommentForm}}

        {% endfor %}
        <button class="btn btn-outline-primary" type="submit" >
            Leave Comment
        </button>
    </form>
    {% endif %}
    
    {% endif %}
    {% else %}
    
    No listing matches this search
    {% endif %}
</div>
    {% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2 class="header" id="listing-title">Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/new_listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2 class="header" id="listing-title">Create New Listing</h2>

    <form class="form " method="POST" enctype="multipart/form-data">
        {{ new_listing_form.as_p }}
        {% csrf_token %}
        <input class="btn btn-outline-primary" type="submit" name="new_listing">
    </form>



{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2 class="header" id="listing-title">Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2 class="header" id="listing-title">Watchlist</h2>

    <ul style="list-style:none;">

        {% if watchlist %}
            
            {% for listing in watchlist.listings.all %}

            
            <div class="card listing" >
                <!-- <li > -->
                
                    <h4>
                        <a href="{% url 'auctions:id' listing.id %}">
                            {{ listing.title }}
                        </a>
                    </h4>
                    
                    <!-- <ul> -->
                        <h6>
                            Owner:
                            <span style="font-weight: normal; color:gray;">
                                {{ listing.user }}
                            </span>
                        </h6>

                        
                        <div class="img-border">
                                {% if listing.image_url %}

                                <img class="img-thumbnail"style="display:inline-block; height:100%; width:100%;object-fit: contain;"src= "{{ listing.image_url.url }}" >
                                {% else %}
                                
                                <img class="img-thumbnail"style="display:inline-block; height:100%; width:100%;object-fit: contain;"src= "https://st4.depositphotos.com/14953852/24787/v/600/depositphotos_247872612-stock-illustration-no-image-available-icon-vector.jpg" >

                                {% endif %}
                            </div>
                        <div style="display:inline;position:absolute;left:14em;bottom:1em;">

                            <h6>
                                <span>
                                    Price: ${{ listing.price }}
                                </span>
                            </h6>
                            <h6>
                                Description: 
                                <span style="font-weight: normal; color:gray;">
                                    {{ listing.details }}
                                </span>
                            </h6>
                            <h6>
                                Category: 
                                <span style="font-weight: normal; color:gray;">
                                    {{ listing.category }}
                                </span>
                            </h6>
                        </div>
                    <!-- </ul> -->
                    
                <!-- </li> -->
            </div>
            <hr>
            {% endfor %}
        {% endif %}
    </ul>

{% endblock %}                